name: Deploy static content to Pages

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20.x

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - env:
          GH_TOKEN: ${{ github.token }}
        run: |
          url=$(gh api "repos/$GITHUB_REPOSITORY/pages" --jq '.html_url')
          echo '<meta http-equiv="Cache-Control" content="no-cache"><meta http-equiv="refresh" content="0; URL='${url}/${{ steps.package-version.outputs.current-version }}'">' > ./docs/ugla-gantt/index.html

      - name: Deploy Redirect
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ github.token }}
          publish_dir: ./docs/ugla-gantt

      - run: npm ci
      - run: npm run docs

      - name: Deploy Docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ github.token }}
          publish_dir: ./docs/ugla-gantt/${{ steps.package-version.outputs.current-version }}
          destination_dir: ${{ steps.package-version.outputs.current-version }}

      # - name: Setup Pages
      #   uses: actions/configure-pages@v4

      # - name: Upload artifact
      #   uses: actions/upload-pages-artifact@v3
      #   with:
      #     path: ./docs/ugla-gantt

      # - name: Deploy to GitHub Pages
      #   id: deployment
      #   uses: actions/deploy-pages@v4
